// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeQYUWtPkxNgXW8i7OeHwY5yxO_VpWMXw',
    appId: '1:48467114153:android:dd2444114604bc9cf151b8',
    messagingSenderId: '48467114153',
    projectId: 'wamya-food-42b8e',
    storageBucket: 'wamya-food-42b8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZ6tYBQyyvvPIlXOK81iek199ZGsz_j0',
    appId: '1:48467114153:ios:a51badf2ccd81e10f151b8',
    messagingSenderId: '48467114153',
    projectId: 'wamya-food-42b8e',
    storageBucket: 'wamya-food-42b8e.appspot.com',
    androidClientId: '48467114153-tacfhod9qbf602s28sm8qdlh0hej8m5s.apps.googleusercontent.com',
    iosClientId: '48467114153-tq4sjir3kpbei0vhj88oi87600epp6tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeleviry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBre8oRZjh0yKWJmyuEPo-pPVXqDJe3wZs',
    appId: '1:48467114153:web:352d606ef0fa43e8f151b8',
    messagingSenderId: '48467114153',
    projectId: 'wamya-food-42b8e',
    authDomain: 'wamya-food-42b8e.firebaseapp.com',
    storageBucket: 'wamya-food-42b8e.appspot.com',
    measurementId: 'G-G59LZDWLXK',
  );
}
